alter session set sql_preprocessor_script='';

alter session set sql_preprocessor_script=fg_security.gm_wrapper_script_fg;

select 'gm3' from olap.casino_game_play_fact;

--
-- Test 1 - Check it works with double-quotes
--
SELECT 'GM' FROM OLAP.CASINO_GAME_PLAY_FACT;
--SELECT 'GM' FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA'))) ;
select 'GM' FROM "OLAP".CASINO_GAME_PLAY_FACT;
--SELECT 'GM' FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA'))) ;
select 'GM' from OLAP."CASINO_GAME_PLAY_FACT";
--SELECT 'GM' FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA'))) ;
select 'GM' from "OLAP"."CASINO_GAME_PLAY_FACT";
--SELECT 'GM' FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA'))) ;

--
-- Test 2 - Check it works with joins
-- 

select 'GM'
FROM "OLAP"."CASINO_GAME_PLAY_FACT" "CASINO_GAME_PLAY_FACT"
INNER JOIN "OLAP"."SITE_DIM" "SITE_DIM" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY");
--SELECT 'GM'
--FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA')))  "CASINO_GAME_PLAY_FACT"
--INNER JOIN "OLAP"."SITE_DIM" "SITE_DIM" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY");

SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "sum:RISK_AMOUNT_USD:ok"
FROM "OLAP"."CASINO_GAME_PLAY_FACT" "CASINO_GAME_PLAY_FACT"
  INNER JOIN "OLAP"."SITE_DIM" "SITE_DIM" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
HAVING (COUNT(1) > 0);

--SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "SUM:RISK_AMOUNT_USD:OK"
--FROM (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA')))  "CASINO_GAME_PLAY_FACT"
--  INNER JOIN "OLAP"."SITE_DIM" "SITE_DIM" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
--  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
--WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
--HAVING (COUNT(1) > 0);

SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "sum:RISK_AMOUNT_USD:ok"
FROM "OLAP"."SITE_DIM" "SITE_DIM" 
  INNER JOIN "OLAP"."CASINO_GAME_PLAY_FACT" "CASINO_GAME_PLAY_FACT" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
HAVING (COUNT(1) > 0);

--SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "SUM:RISK_AMOUNT_USD:OK"
--FROM "OLAP"."SITE_DIM" "SITE_DIM" 
--  INNER JOIN (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA')))  "CASINO_GAME_PLAY_FACT" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
--  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
--WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
--HAVING (COUNT(1) > 0);

--
-- Test 3 - check it works with CREATE VIEW
--
create or replace view myview as
SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "sum:RISK_AMOUNT_USD:ok"
FROM "OLAP"."SITE_DIM" "SITE_DIM" 
  INNER JOIN "OLAP"."CASINO_GAME_PLAY_FACT" "CASINO_GAME_PLAY_FACT" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
HAVING (COUNT(1) > 0);
--CREATE OR REPLACE VIEW MYVIEW AS
--SELECT SUM("CASINO_GAME_PLAY_FACT"."RISK_AMOUNT_USD") AS "SUM:RISK_AMOUNT_USD:OK"
--FROM "OLAP"."SITE_DIM" "SITE_DIM" 
--  INNER JOIN (SELECT * FROM OLAP.CASINO_GAME_PLAY_FACT WHERE CASINO_SITE_KEY IN (SELECT SD.SITE_KEY FROM OLAP.SITE_DIM SD WHERE SD.SITE_NAME IN ('BODOG_ASIA','BOVADA')))  "CASINO_GAME_PLAY_FACT" ON ("CASINO_GAME_PLAY_FACT"."CASINO_SITE_KEY" = "SITE_DIM"."SITE_KEY")
--  INNER JOIN "OLAP"."PLAYER_PROFILE_DIM" "PLAYER_PROFILE_DIM" ON ("CASINO_GAME_PLAY_FACT"."PLAYER_PROFILE_KEY" = "PLAYER_PROFILE_DIM"."PLAYER_PROFILE_KEY")
--WHERE (((NOT "CASINO_GAME_PLAY_FACT"."CURRENCY_KEY" IS NULL) AND (NOT "CASINO_GAME_PLAY_FACT"."CHANNEL_KEY" IS NULL)) AND (NOT "CASINO_GAME_PLAY_FACT"."VENDOR_KEY" IS NULL))
--HAVING (COUNT(1) > 0);



